MODEL:
  TYPE: anynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: res_stem_in
  STEM_W: 64
  STEM_K: 7
  BLOCK_TYPE: res_basic_block
  STRIDES: [[1], [2], [2], [2]]
  DEPTHS: [[3], [4], [6], [3]]
  WIDTHS: [[64], [128], [256], [512]]
  BOT_MULS: [1, 1, 1, 1]
  GROUP_WS: [[64], [128], [256], [512]]
  DEVICES: ["dsp"]
  HEAD_DEVICE: "dsp"
  STEM_DEVICE: "dsp"
  MERGE_DEVICE: "dsp"
  ORIGINAL_WIDTHS: [64, 128, 256, 512]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.2
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 256
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 200
NUM_GPUS: 8
OUT_DIR: .
