MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: res_stem_in
  STEM_W: 64
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  DEPTHS: [[3, 2], [3, 3], [5, 5], [3, 2]]
  WIDTHS: [[128, 224], [320, 256], [672, 544], [1216, 1152]]
  BOT_MULS: [0.25, 0.25, 0.25, 0.25]
  GROUP_WS: [[32, 56], [80, 64], [168, 136], [304, 288]]
  DEVICES: ["cpu", "dsp"]
  HEAD_DEVICE: "cpu"
  STEM_DEVICE: "cpu"
  MERGE_DEVICE: "cpu"
  ORIGINAL_WIDTHS: [352, 576, 1216, 2368]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.2
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 256
  DISTILL: True
  TEACHER: resnet
  TEACHER_NAME: ResNet-50
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 200
DATA_LOADER:
  MODE: ffcv
NUM_GPUS: 4
OUT_DIR: .
